### ISSUE TITLE
Including stylesheet on all admin pages

### ISSUE THREAD

**Issue by kjbenk** [mpeshev/DX-Plugin-Base#2]
This is a cool plugin, but aren't you including your stylesheet on all admin pages?

This is the function call: https://github.com/mpeshev/DX-Plugin-Base/blob/master/dx-plugin-base.php#L149

**Comment by mpeshev** [comment]
Thanks for the feedback! 

That's purely for demonstrative purposes. Often there are style updates that affect the entire admin area, so it's not a use case that is unheard of.

Beginner developers have a hard time learning concepts, which is why I've demonstrated how you can enqueue something globally, or conditionally based on the current hook.

**Comment by kjbenk** [comment]
Have you ever thought about using a different way to only display scripts and stylesheets on a specific page.  Here is an example from one of our plugins.

```$page = add_submenu_page(
	    	'tools.php'
	    	__('My Page'),
	    	__('My Page'),
	    	'manage_options',
	    	'my-page',
	    	array('MyClass', 'myFunction')
	    );
add_action("admin_print_scripts-$page", array('MyClass', 'myScripts'));```

**Comment by mpeshev** [comment]
Yes, but honestly I wouldn't consider that as "standard". I've used the plugin as a training module for over 300 students and more than 20 interns and juniors, and I know that many of them have a hard time with more complex concepts, which is why I try to cover the basics of everything without getting into too much details.

Happy to review a PR from you to README.md which serves as a documentation if you'd like to extend the list with different cases, since that would be more applicable and helpful in my opinion.

**Comment by kjbenk** [comment]
I was just trying to help you create a better base plugin for people to build off of.  Like I said before I think this is a great start :), but I would say that in my experience I have had a lot of plugin conflicts because of poor file inclusion.

I am only trying to stop plugin conflicts form happening again, but if you are using this as more of a teaching tool and not a base framework then maybe it wouldn't matter like you said.
